### PR TITLE
Issue6 : Reporte de balance

### PR DESCRIPTION
**Pull request by jcapoduri**

### CODE REVIEW

**Comment by jcapoduri** [comment]
Deberias correr un composer update para que anden bien los reportes

**Comment by Valentind88** [comment]
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Neodymium\Controllers\AccountingReportController::exportResultAsPlan(), 1 passed in C:\dev\neodymium\app\controllers\AccountingReportController.php on line 243 and exactly 3 expected in C:\dev\neodymium\app\controllers\AccountingReportController.php:208 Stack trace: #0 C:\dev\neodymium\app\controllers\AccountingReportController.php(243): Neodymium\Controllers\AccountingReportController->exportResultAsPlan(Object(Phalcon\Mvc\Model\Resultset\Simple)) #1 C:\dev\neodymium\app\controllers\AccountingReportController.php(90): Neodymium\Controllers\AccountingReportController->exportResultAsSpreadsheet('plan', Object(Phalcon\Mvc\Model\Resultset\Simple), NULL, NULL, NULL, NULL) #2 [internal function]: Neodymium\Controllers\AccountingReportController->postAction() #3 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(Neodymium\Controllers\AccountingReportController), 'postAction', Array) #4 [internal function]: Phalcon\Dispatcher->_dispatch() #5 [i in C:\dev\neodymium\app\controllers\AccountingReportController.php on line 208

**Comment by jcapoduri** [comment]
Deberian estar solucionados los issues, probalos y si esta ok, mergea el pull request asi sigo con el diario

**Comment by jcapoduri** [comment]
lo acabo de probar en mi maquina con windows 10 y anda, quedan detalles que fui viendo en el branch que le sigue, lo mergeo, cierro el issue y abro otro para validar resultados generales

**Pull request closed without merging**
